name: .NET

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]
        
jobs:
    build:
        runs-on: ubuntu-latest
        
        env:
            DOTNET_VERSION: '9.0.x'
        
        steps:

        - uses: actions/checkout@v4
          
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}
            
        - name: Restore dependencies
          run: dotnet restore
          
        - name: Build 
          run: dotnet build --configuration Release --no-restore

        - name: Test
          run: dotnet test --configuration Release --no-build --verbosity normal
          
        - name: Publish app
          run: dotnet publish --configuration Release --no-restore --output ./publish
            
        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: publish
            path: publish
